server:
  port : ${SERVER_PORT:8080}
spring:
  jpa:
    open-in-view: false
    database-platform: 'org.hibernate.dialect.PostgreSQLDialect'
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: true
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  datasource:
    url: 'jdbc:postgresql://postgres:5432/rinhabackend'
    username: rinhabackend
    password: mypassword
    hikari:
      maximum-pool-size: 40
      connection-timeout: 30000
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    enabled: true
